export const type = {
  ROOM_CHECK: {
    RESPONSE_FAILURE: "CHECK_ROOM_RESPONSE_FAILURE",
    RESPONSE_SUCCESS: "CHECK_ROOM_RESPONSE_SUCCESS",
  },
  ROOM_DESTR0Y: {
    RESPONSE_FAILURE: "DESTRY_ROOM_RESPONSE_FAILURE",
    RESPONSE_SUCCESS: "DESTRY_ROOM_RESPONSE_SUCCESS",
  },
};
